name: Docker pull requests

on:
  pull_request:
    paths:
      - 'scripts/tvm_cli/**'

jobs:

  dockerfile-lint:

    runs-on: ubuntu-latest
    continue-on-error: true

    container:
      image: hadolint/hadolint:latest-debian

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting
        run: |
          hadolint scripts/tvm_cli/Dockerfile.amd64
          hadolint scripts/tvm_cli/Dockerfile.arm64

  python-lint:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install pylint
          find . -name "*.py" | xargs pylint \
            --disable=import-error \
            --disable=invalid-name \
            --disable=missing-module-docstring \
            --disable=redefined-builtin \
            --disable=too-many-locals \
            --disable=too-many-statements \
            --disable=broad-except \
            --disable=consider-using-sys-exit

  cpp-lint:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --suppress=missingIncludeSystem .

  shell-lint:

    runs-on: ubuntu-latest
    continue-on-error: true

    container:
      image: koalaman/shellcheck-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linting
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck --shell=bash
        shell: sh

  setup-docker-arm64:
      runs-on: ARM64

      steps:
        - name: Install docker
          run: |
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo groupadd docker || true
            sudo usermod -aG docker ${USER}
            sudo chmod 666 /var/run/docker.sock

        - name: Prune docker
          run: docker system prune -a -f

  build-docker:
      needs: [dockerfile-lint, python-lint, cpp-lint, shell-lint, setup-docker-arm64]

      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, ARM64]
      env:
        IMAGE_NAME: autoware/model-zoo-tvm-cli
        TAG_NAME: bleedingedge

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: image build
          run: |
            ./scripts/tvm_cli/build.sh -i "$IMAGE_NAME" -t "$TAG_NAME" --ci

  build-docker-cuda:
      needs: [dockerfile-lint, python-lint, cpp-lint, shell-lint, setup-docker-arm64]

      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, ARM64]
      env:
        IMAGE_NAME: autoware/model-zoo-tvm-cli
        TAG_NAME: bleedingedge-cuda

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: image build with cuda
          run: |
            ./scripts/tvm_cli/build.sh -c -i "$IMAGE_NAME" -t "$TAG_NAME" --ci
